DATA CLEANING AND MANIPULATION

single dimensional array

In [ ]:
import numpy as np
sda=np.array([1,2,3,76,8,9])
tda=np.array([[1,2],[3,4],[4,5],[7,6]])
trda=np.array([[[1,6,7,2],[35,6,7,8]],[[5,7,8,6],[5,8,9,0]]])
print(sda)
print(tda)
print(trda)


[ 1  2  3 76  8  9]
[[1 2]
 [3 4]
 [4 5]
 [7 6]]
[[[ 1  6  7  2]
  [35  6  7  8]]

 [[ 5  7  8  6]
  [ 5  8  9  0]]]


printing dimension

In [ ]:
print(sda.ndim)
print(tda.ndim)
print(trda.ndim)

1
2
3


changing dimension 

In [ ]:
print(np.array([1,2,3,4,5], ndmin=3))
print(np.array([1,2,3,4,5], ndmin=2))
trda=np.array([[[1,2],[3,4]],[[5,6],[5,8]]],ndmin=2) #doesnt work
print(trda)

[[[1 2 3 4 5]]]
[[1 2 3 4 5]]
[[[1 2]
  [3 4]]

 [[5 6]
  [5 8]]]


to find the shape of the array

In [ ]:
trd=np.array([[[1,6,7,2],[35,6,7,8]],[[5,7,8,6],[5,8,9,0]]])
print(sda.shape)
print(tda.shape)
print(trd.shape)

(6,)
(4, 2)
(2, 2, 4)


reshaping

In [ ]:
print(sda.reshape(2,3))
print('tda is\n',tda)
print(tda.reshape(2,4))
print(tda.reshape(4,2))
print(tda.reshape(8,1))
print(trd.reshape(4,4))
tdim=np.array([[[1,2,3],[2,3,4]],[[3,5,6],[4,3,6]]]) #converting 3 to 2 dim
rtdm=tdim.reshape(6,2)
print(rtdm)

[[ 1  2  3]
 [76  8  9]]
tda is
 [[1 2]
 [3 4]
 [4 5]
 [7 6]]
[[1 2 3 4]
 [4 5 7 6]]
[[1 2]
 [3 4]
 [4 5]
 [7 6]]
[[1]
 [2]
 [3]
 [4]
 [4]
 [5]
 [7]
 [6]]
[[ 1  6  7  2]
 [35  6  7  8]
 [ 5  7  8  6]
 [ 5  8  9  0]]
[[1 2]
 [3 2]
 [3 4]
 [3 5]
 [6 4]
 [3 6]]


flattening concept
reshape 3 or 2 dim to 1 dim

In [ ]:
trd=np.array([[[1,6,7,2],[35,6,7,8]],[[5,7,8,6],[5,8,9,0]]])
print(trd.reshape(-1))



[ 1  6  7  2 35  6  7  8  5  7  8  6  5  8  9  0]


ARange to create array automatically without passing values

In [ ]:
a=np.arange(10)
print('a is',a)
b=np.arange(10,40,4)
print('b is',b)
print(b.reshape(2,4))
print(b.reshape(4,2))

a is [0 1 2 3 4 5 6 7 8 9]
b is [10 14 18 22 26 30 34 38]
[[10 14 18 22]
 [26 30 34 38]]
[[10 14]
 [18 22]
 [26 30]
 [34 38]]


using two brackets for creating zero matrix and ones matrix

In [ ]:
zerom=np.zeros((3,3))
onem=np.ones((3,3))
print('zeros matrix \n',zerom)
print('ones matrix \n',onem)

zeros matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones matrix 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


empty matrix only giving dimensions but not giving values for the matrix

In [ ]:
emp=np.empty((6,3))
print(emp)

[[0.00000000e+000 2.35541533e-312 2.41907520e-312]
 [2.14321575e-312 2.46151512e-312 2.31297541e-312]
 [2.35541533e-312 2.05833592e-312 2.22809558e-312]
 [2.56761491e-312 2.48273508e-312 2.05833592e-312]
 [2.05833592e-312 2.29175545e-312 2.07955588e-312]
 [2.14321575e-312 2.47672538e-143 8.80067056e+199]]


full matrix giving dimensions and which value to be filled in  the matrix

In [ ]:
fulm=np.full((2,5),8)
print(fulm)

[[8 8 8 8 8]
 [8 8 8 8 8]]


eye matrix (identity matrix) must square matrix dimension is valid , diagonal will be  1

In [ ]:
eyem=np.eye(6,6)
print(eyem)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


linspace parameter( strating number, ending number, no of columns)

In [ ]:
lsm=np.linspace(10,40, num=10)
print(lsm)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.         33.33333333 36.66666667 40.        ]


random function always print the number between 0 and 1

In [ ]:
rm=np.random.random((3,5))
print(rm)

[[0.47373414 0.50544914 0.01417274 0.9668241  0.52029634]
 [0.39749187 0.97349321 0.82427204 0.08604936 0.89661967]
 [0.21776422 0.66273315 0.77881213 0.12779582 0.48065406]]


randint whole number only print parameter are minimum value, maximum value, size or no of columns

In [ ]:
roint=np.random.randint(1,89,10)
rint=np.random.randint(0,10,(3,4)) #2 dim randint
print(rint)
print(roint)

[[9 3 2 7]
 [4 6 1 5]
 [1 4 1 9]]
[66  4 19  6 55 10 77 79  4 74]


zeros_like filling the existing array with zeros

In [ ]:
ab=np.arange(10)
abc=ab.reshape(5,2)
print(abc)
zab=np.zeros_like(abc)
print(zab)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


ones like filling the existing array with ones

In [ ]:
zab=np.ones_like(abc)
print(zab)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


full like replace the existing values with the given value

In [ ]:
zab=np.full_like(abc,4)
print(zab)

[[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]


integer array indexing

In [ ]:
arr=np.arange(19,9,-1)
ar=np.arange(1,6,2)
print(ar)
print(arr)
print(ar==7)
ar1=np.arange(1,20,2)
print(ar1)
print(ar1[1:5])

[1 3 5]
[19 18 17 16 15 14 13 12 11 10]
[False False False]
[ 1  3  5  7  9 11 13 15 17 19]
[3 5 7 9]


arithmetic operation 

In [ ]:
a1=np.arange(1,10,2)
a2=np.arange(2,11,2)
print(a1)
print(a2)
addition=np.add(a1,a2)
print(addition)
subtraction=np.subtract(a1,a2)
multiplication=np.multiply(a1,a2)
division=np.divide(a1,a2)
print(subtraction)
print(multiplication)
print(division)


[1 3 5 7 9]
[ 2  4  6  8 10]
[ 3  7 11 15 19]
[-1 -1 -1 -1 -1]
[ 2 12 30 56 90]
[0.5        0.75       0.83333333 0.875      0.9       ]


reciprocal must include after anyone number

In [ ]:
arr1=np.array([2.,3,4,5,1,4])
print(np.reciprocal(arr1))

[0.5        0.33333333 0.25       0.2        1.         0.25      ]


modulus greater number divides smaller gives correct answer otherwise it gives the smaller numbers as the answer

In [ ]:
print(a1)
print(a2)
print(np.mod(a2,a1))
print(np.remainder(a2,a1))

[1 3 5 7 9]
[ 2  4  6  8 10]
[0 1 1 1 1]
[0 1 1 1 1]


power

In [ ]:
arr2=np.arange(0,5)
print(np.power(arr2,3)) #cube
print(np.power(arr2,2)) #square
print(np.power(a1,a2))


[ 0  1  8 27 64]
[ 0  1  4  9 16]
[         1         81      15625    5764801 3486784401]


two array  a and b, a is sequencly declared 0 to 11, 13 to 24  b array reshape apply reciprocal AFTER MUltiplication and addition

In [ ]:
a=np.arange(12,dtype=float)
print(a)
b=np.arange(13,25,1,dtype=float)
print(b)
a1=a.reshape(4,3)
b1=b.reshape(4,3)
print(a1)
print(b1)
addit=np.add(a1,b1)
print(addit)
mul=np.multiply(a1,b1)
print(mul)
print(np.reciprocal(addit))
print(np.reciprocal(mul))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]
 [22. 23. 24.]]
[[13. 15. 17.]
 [19. 21. 23.]
 [25. 27. 29.]
 [31. 33. 35.]]
[[  0.  14.  30.]
 [ 48.  68.  90.]
 [114. 140. 168.]
 [198. 230. 264.]]
[[0.07692308 0.06666667 0.05882353]
 [0.05263158 0.04761905 0.04347826]
 [0.04       0.03703704 0.03448276]
 [0.03225806 0.03030303 0.02857143]]
[[       inf 0.07142857 0.03333333]
 [0.02083333 0.01470588 0.01111111]
 [0.00877193 0.00714286 0.00595238]
 [0.00505051 0.00434783 0.00378788]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in reciprocal
  


transpose of matrix

In [ ]:
aa=np.arange(0,12,1)
aa1=aa.reshape(4,3)
print(aa1)
print(np.transpose(aa1))
print(b1)
print(b1.transpose())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]
 [22. 23. 24.]]
[[13. 16. 19. 22.]
 [14. 17. 20. 23.]
 [15. 18. 21. 24.]]


vsplit

In [ ]:
a1=np.random.randint(1,6,size=12)
a11=a1.reshape(4,3)
print(a11)
#print(np.vsplit(a1,2))   produce error cannot split  onr dimensional array
print(np.vsplit(a11,2))

[[3 3 1]
 [5 5 3]
 [2 4 5]
 [3 2 1]]
[array([[3, 3, 1],
       [5, 5, 3]]), array([[2, 4, 5],
       [3, 2, 1]])]


hsplit

In [ ]:
print(np.hsplit(a11,3))

[array([[3],
       [5],
       [2],
       [3]]), array([[3],
       [5],
       [4],
       [2]]), array([[1],
       [3],
       [5],
       [1]])]


2 dim concatenate

In [ ]:
ar1=np.arange(3,7)
print(ar1)
ar11=ar1.reshape(2,2)
print(ar11)
ar2=np.arange(14,18)
ar22=ar2.reshape(2,2)
print(ar22)
print(np.concatenate((ar11,ar22),axis=0))
print(np.concatenate((ar11,ar22),axis=1))

[3 4 5 6]
[[3 4]
 [5 6]]
[[14 15]
 [16 17]]
[[ 3  4]
 [ 5  6]
 [14 15]
 [16 17]]
[[ 3  4 14 15]
 [ 5  6 16 17]]


vstack

In [ ]:
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.array([3,4,5])
print(np.vstack((a,b,c)))

[[1 2 3]
 [2 3 4]
 [3 4 5]]


hstack

In [ ]:
print(np.hstack((a,b,c)))

[1 2 3 2 3 4 3 4 5]


3 dim concatenate

In [ ]:
ar1=np.arange(0,16)
print(ar1)
ar11=ar1.reshape(2,2,4)
print(ar11)
ar2=np.arange(10,26)
ar22=ar2.reshape(2,2,4)
print(ar22)
print(np.concatenate((ar11,ar22),axis=0))
print(np.concatenate((ar11,ar22),axis=1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [10 11 12 13]
  [14 15 16 17]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [18 19 20 21]
  [22 23 24 25]]]


reshaping to 3 dim

In [ ]:
ar1=np.arange(0,90)
ar11=ar1.reshape(5,6,3)#(no of 2 dim array, no of rows, no of columns)
print(ar11)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]]

 [[72 73 74]
  [75 76 77]
  [78 79 80]
  [81 82 83]
  [84 85 86]
  [87 88 89]]]


MATHEMATICAL FUNCTIONS

trignometric

In [ ]:
a1=np.array([0,30,45,60,90,120,150,180])
print(np.sin(a1*np.pi/180))   #a1*np.pi value/180 is used to convert the number to radiant value
print(np.cos(a1*np.pi/180))
print(np.tan(a1*np.pi/180))
print(np.arcsin(a1*np.pi/180))
print(np.arccos(a1*np.pi/180))
print(np.arctan(a1*np.pi/180))

[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 8.66025404e-01 5.00000000e-01 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]
[0.         0.55106958 0.90333911        nan        nan        nan
        nan        nan]
[1.57079633 1.01972674 0.66745722        nan        nan        nan
        nan        nan]
[0.         0.48234791 0.66577375 0.80844879 1.00388482 1.12533883
 1.20592739 1.26262726]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in arcsin
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in arccos
  


applying analog circuits of trignometric is HYPERBOLIC(analog format of trignometric)

In [ ]:
 a1=np.array([0,30,45,60,90,120,150,180])
print(np.sinh(a1*np.pi/180))   #a1*np.pi value/180 is used to convert the number to radiant value
print(np.cosh(a1*np.pi/180))
print(np.tanh(a1*np.pi/180))
print(np.arcsinh(a1*np.pi/180))
print(np.arccosh(a1*np.pi/180))
print(np.arctanh(a1*np.pi/180))

[ 0.          0.54785347  0.86867096  1.24936705  2.3012989   3.99869134
  6.8176233  11.54873936]
[ 1.          1.14023832  1.32460909  1.60028686  2.50917848  4.12183605
  6.89057236 11.59195328]
[0.         0.48047278 0.6557942  0.78071444 0.91715234 0.97012382
 0.98941321 0.99627208]
[0.         0.50221899 0.72122549 0.91435666 1.23340312 1.48507048
 1.69018317 1.86229574]
[       nan        nan        nan 0.30604211 1.02322748 1.36981867
 1.61690509 1.81152627]
[0.         0.58128501 1.05930617        nan        nan        nan
        nan        nan]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in arccosh
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in arctanh
  import sys


rounding

In [ ]:
a=np.array([2.4556,67.7567,4.789,3.567,9.988,7.564])
print(np.around(a,2))
b=np.floor(a)
print(b)
print(np.ceil(a))

[ 2.46 67.76  4.79  3.57  9.99  7.56]
[ 2. 67.  4.  3.  9.  7.]
[ 3. 68.  5.  4. 10.  8.]


exponential format of number e power x (e=2.7182)

In [ ]:
a=np.arange(1,6)
print(np.exp(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


logarthmic value

In [ ]:
print(np.log(a)) #log of base 1 values by default base is 1
print(np.log2(a)) #base is 2
print(np.log10(a)) #base  is 10

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


complex function: ISREAL IS finding given value is real or imaginary( output willbe boolean) imaginary always will be j 

CONJUGATE function reverse the sign(+ to -)

In [ ]:
a=np.array([2,3+3j,78,99,4+2j])
print(np.isreal(a))
print(np.conj(a))

[ True False  True  True False]
[ 2.-0.j  3.-3.j 78.-0.j 99.-0.j  4.-2.j]


LINEAR ALGEBRA

dot matrix (sum of product of the element)

In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,3])
print(np.dot(a,b)) #one dim dot

a1=np.arange(0,12)
a2=np.arange(10,22)
a11=a1.reshape(4,3)
a22=a2.reshape(3,4)
print(a1)
print(a2)
print(a11)
print(a22)
print('dot product of 2 dimension\n',np.dot(a11,a22)) #2 dimension dot product

32
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[10 11 12 13 14 15 16 17 18 19 20 21]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
dot product of 2 dimension
 [[ 50  53  56  59]
 [176 188 200 212]
 [302 323 344 365]
 [428 458 488 518]]


vdot product matrix
1 st element multiply + 2 nd element multiply+.....+ n element multiply   



In [ ]:
print(a1)
print(a2)
print(a11)
print(a22)
print(np.vdot(a1,a2))
print(np.vdot(a11,a22))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[10 11 12 13 14 15 16 17 18 19 20 21]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
1166
1166


inner and outer product

In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([4,5,7,8])
print(np.inner(a1,a2)) #1*4 +2*5 +3*7+4*8
print(np.outer(a1,a2)) #4*1    5*1   7*1   8*1
                       #4*2    5*2   7*2   8*2
                       #4*3    5*3   7*3   8*3
                       #4*4    5*4   7*4   8*4

67
[[ 4  5  7  8]
 [ 8 10 14 16]
 [12 15 21 24]
 [16 20 28 32]]


determinant   

In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))
b=np.random.randint(1,10,size=9)
print(b)
b1=b.reshape(3,3)
print(b1)
print(np.linalg.det(b1))

-2.0000000000000004
[8 6 7 8 9 8 2 8 5]
[[8 6 7]
 [8 9 8]
 [2 8 5]]
25.99999999999999


inverse matrix (adj(a)*1/det(a)

In [ ]:
print(np.linalg.inv(b1))
print(np.linalg.inv(a))

[[-0.73076923  1.         -0.57692308]
 [-0.92307692  1.         -0.30769231]
 [ 1.76923077 -2.          0.92307692]]
[[-2.   1. ]
 [ 1.5 -0.5]]


eigen value

In [ ]:
a=np.array([[0,1],[-2,-3]])
print(np.linalg.eig(a))

(array([-1., -2.]), array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]]))


Rank matrix only applicable for square matrix(non zero rows)

In [ ]:
a=np.array([[2,24],[4,48]])
print(np.linalg.matrix_rank (a))
print(np.linalg.matrix_rank(b1))
c=np.array([[1,2,3],[2,3,4],[3,5,7]])
print(np.linalg.matrix_rank(c))

1
3
2


matrix multiplication similar to dot product

In [ ]:

a=np.array([1,2,3,4])
b=np.array([2,3,4,3])
print(np.matmul(a,b)) #one dim dot

a1=np.arange(0,12)
a2=np.arange(10,22)
a11=a1.reshape(4,3)
a22=a2.reshape(3,4)
print(np.matmul(a11,a22))

32
[[ 50  53  56  59]
 [176 188 200 212]
 [302 323 344 365]
 [428 458 488 518]]


solve method

In [ ]:
a=np.array([[4,3],[-5,9]])
b=np.array([[20],[26]])
print(np.linalg.solve(a,b)) #2 cross 2 matrix
a=np.array([[4,3,8],[-5,9,4],[2,5,7]])
b=np.array([[20],[26],[49]])
print(np.linalg.solve(a,b))  # 3cross 3 matrix

[[2.]
 [4.]]
[[ 36.88372093]
 [ 36.55813953]
 [-29.65116279]]


trace method (sum of diagonal values) only square matrix is valid

In [ ]:
print(a)
print(np.trace(a)) #4+9+7
a1=np.array([[4,3],[-5,9]])
print(a1)
print(np.trace(a1)) #4+9

[[ 4  3  8]
 [-5  9  4]
 [ 2  5  7]]
20
[[ 4  3]
 [-5  9]]
13


broadcasting ( perform impossible operation for eg addition of different shape matrix)

In [ ]:
a=np.array(5)
b=np.array([1,2,4,56])
c=np.array([[1,2,5,6],[6,7,3,4]])
d=np.array([[[2,3,4,5],[8,4,6,8]],[[4,7,6,7],[9,7,8,9]]])
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(a+b) #0 with 1
print(a+c)  #0 with 2
print(a+d) #0 with 3
print(b+c) #1 with 2
print(b+d) #1 with 3
print(c+d) #2 with 3


()
(4,)
(2, 4)
(2, 2, 4)
[ 6  7  9 61]
[[ 6  7 10 11]
 [11 12  8  9]]
[[[ 7  8  9 10]
  [13  9 11 13]]

 [[ 9 12 11 12]
  [14 12 13 14]]]
[[ 2  4  9 62]
 [ 7  9  7 60]]
[[[ 3  5  8 61]
  [ 9  6 10 64]]

 [[ 5  9 10 63]
  [10  9 12 65]]]
[[[ 3  5  9 11]
  [14 11  9 12]]

 [[ 5  9 11 13]
  [15 14 11 13]]]


STASTICAL FUNCTIONS

In [ ]:
a=np.array(5)
b=np.array([1,2,4,9])
c=np.array([[1,2,5,6],[6,7,3,4]])
d=np.array([[[2,3,4,5],[8,4,6,8]],[[4,7,6,7],[9,7,8,9]]])
print(np.amin(b))   #minimum value
print(np.amax(b))   # maximum value
print(np.amin(d))
print(np.amax(d))
print(np.mean(b))  #mean of the b array
print(np.mean(c))
e=np.array([1,3,5,87,9])
print(np.median(b))   #median of the b array
print(np.median(e))
print(np.std(b))   #standard deviation of the b array
print(np.std(c))
print(np.var(b))   #variance of the b array
print(np.var(c))
#average is similar to mean but the advantage of average is it also calculates the average weight of the graph
wght=np.array([2,4,6,8])
print(np.average(b))
print(np.average(b,weights=wght))
print(np.percentile(c,50)) #50 percent are less than 4  
print(np.percentile(c,50,axis=0))#axis=1 row, axis=0 is column
print(np.percentile(c,50,axis=1))
print(np.ptp(c)) #ptp is range
print(np.ptp(c,axis=1))
print(np.ptp(c,axis=0))


1
9
2
9
4.0
4.25
3.0
5.0
3.082207001484488
1.984313483298443
9.5
3.9375
4.0
5.3
4.5
[3.5 4.5 4.  5. ]
[3.5 5. ]
6
[5 4]
[5 5 2 2]


STRING FUNCTION

string operations

In [ ]:
print(np.char.lower(['HELLO WORLD']))

['hello world']


In [ ]:
print(np.char.upper(['hello world']))

['HELLO WORLD']


In [ ]:
print(np.char.capitalize('hello world'))#first letter of the string will be upper

Hello world


In [ ]:
print(np.char.title(['hello world']))#every first letter will be upper case

['Hello World']


In [ ]:
print(np.char.split('hello world i am pavithira'))#split every word with comma

['hello', 'world', 'i', 'am', 'pavithira']


In [ ]:
print(np.char.join('+','hello world'))#join every letter with +
print(np.char.join(' ','hello world'))#join every character with white space

h+e+l+l+o+ +w+o+r+l+d
h e l l o   w o r l d


In [ ]:
print(np.char.strip(['     hi    world      ', '    i am pavi        ']))#strip removes white space before and after the every string

['hi    world' 'i am pavi']


In [ ]:
a='hello world'
print(a)
print(np.char.center(a,30,'*'))#centering the the given string with in the 30 space ,other space will be star
print(np.char.center('hi world',30,' '))# center the given string with in 30 space other space will be white space

hello world
*********hello world**********
           hi world           


In [ ]:
a=['hi','world']
print(np.char.encode(a,encoding='utf-32',errors=None)) #unicode transformation format(can use 8,16,32,64 bit)
print(np.char.encode(a,encoding='cp037',errors=None))#'cp037 is cypher format
print(np.char.encode(a,encoding=None,errors=None))#encode is none gives the input with b in the front 

[b'\xff\xfe\x00\x00h\x00\x00\x00i'
 b'\xff\xfe\x00\x00w\x00\x00\x00o\x00\x00\x00r\x00\x00\x00l\x00\x00\x00d']
[b'\x88\x89' b'\xa6\x96\x99\x93\x84']
[b'hi' b'world']


In [ ]:
b=np.char.encode(a,encoding='cp037',errors=None) 
print(b)
print(np.char.decode(b,encoding='cp037'))#decode the cp037 format
print(np.char.decode(b,encoding='cp500'))#decode the cp500 format
b=np.char.encode(a,encoding='utf-8',errors=None) #only utf-8 is work and cp057 and cp500 will work others wont work
print(b)
print(np.char.decode(b,encoding='utf-8'))

[b'\x88\x89' b'\xa6\x96\x99\x93\x84']
['hi' 'world']
['hi' 'world']
[b'hi' b'world']
['hi' 'world']


In [ ]:
a=['hi','hello']#np.ljust is left justifies the given string
width=10
print(np.char.ljust(a,width,'*'))#left justifies the string in the space 10 using *  
print(np.char.ljust(a,8,' ')) #left justifies the string in the space 8 using white space

['hi********' 'hello*****']
['hi      ' 'hello   ']


In [ ]:
print(np.char.rjust(a,10,'^'))#right justifies the string in the space 10 using ^

['^^^^^^^^hi' '^^^^^hello']


STRING INFORMATION

In [ ]:
a=np.array(['hello','hi','how','are ','yow'])
print(np.char.count(a,'h'))#counts the no of h character in each string

[1 1 1 0 0]


In [ ]:
print(np.char.find(a,'h'))#find the 1 st index where the h is present in each string
print(np.char.find(a,'ow')) #find() : find the lowest index of the given substring(ow)
print(np.char.find(a,' '))#if the substring is not present in the string then it returns -1
print(np.char.find(a,'l'))

[ 0  0  0 -1 -1]
[-1 -1  1 -1  1]
[-1 -1 -1  3 -1]
[ 2 -1 -1 -1 -1]


In [ ]:
print(np.char.rfind(a,'l'))#find the highest index of the substring

[ 3 -1 -1 -1 -1]


In [ ]:
b=np.array(['hello5','2','3.6','hai'])#return true if the given string is numeric(whole number)
print(np.char.isnumeric(b))

[False  True False False]


In [ ]:
print(np.char.isdigit(b))#returns true if the given string is digit(whole number) otherwise returns false

[False  True False False]


In [ ]:
print(np.char.isdecimal(b))#returns true if the given string is decimal(whole number)

[False  True False False]


In [ ]:
print(np.char.isalpha(b))#returns true if the string is alphabets

[False False False  True]


In [ ]:
c=np.array(['HELLO','every one','How','are','you',' ','iam1st']) #returns true if all the characters in the string is lowercase
print(np.char.islower(c))

[False  True False  True  True False  True]


In [ ]:
print(np.char.isupper(c))#returns true if all the characters in the string is uppercase

[ True False False False False False False]


In [ ]:
print(np.char.isspace(c)) # returns true only if the string contains only white space

[False False False False False  True False]


In [ ]:
d='Hello World How Are You'
print(np.char.istitle(d)) #return true if only first character of the every string is uppercase otherwise false
print(np.char.istitle(c))

True
[False False  True False False False False]


string comparition(all output will be boolean)

In [ ]:
print(np.char.equal('pavi','pavi')) #returns true if the both strings are equal
print(np.char.equal('pavi','PaVi'))
print(np.char.equal('pavi','swar'))

True
False
False


In [ ]:
print(np.char.not_equal('pavi','pavi')) #returns true if the both strings are not equal
print(np.char.not_equal('pavi','PaVi'))
print(np.char.not_equal('pavi','swar'))

False
True
True


In [ ]:
print(np.char.greater('aaa','aa'))#returns true if the total of the ascii value in first string is greater than total of the ascii value second string
print(np.char.greater('aa','aaa'))
print(np.char.greater('aaa','bbb'))
print(np.char.greater('bbb','aaa'))
print(np.char.greater('aa','11'))
print(np.char.greater('zz','aaa'))
print(np.char.less('aa','aaa'))#returns true if the total of the ascii value in first string is lesser than total of the ascii value second string
print(np.char.less('aaa','aa'))
print(np.char.less('aaa','bbb'))
print(np.char.less('bbb','aaa'))
print(np.char.less('aa','11'))
print(np.char.less('zz','aaa'))

True
False
False
True
True
True
True
False
True
False
False
False


In [ ]:
print(np.char.greater_equal('aaa','aa'))#returns true if the total of the ascii value in first string is greater than total of the ascii value second string
print(np.char.greater_equal('aa','aaa'))
print(np.char.greater_equal('aaa','bbb'))
print(np.char.greater_equal('bbb','aaa'))
print(np.char.greater_equal('aa','11'))
print(np.char.greater_equal('zz','aaa'))
print(np.char.greater_equal('aaa','aaa'))
print(np.char.less_equal('aa','aaa'))#returns true if the total of the ascii value in first string is lesser than total of the ascii value second string
print(np.char.less_equal('aaa','aa'))
print(np.char.less_equal('aaa','bbb'))
print(np.char.less_equal('bbb','aaa'))
print(np.char.less_equal('aa','11'))
print(np.char.less_equal('zz','aaa'))
print(np.char.less_equal('aaa','aaa'))

True
False
False
True
True
True
True
True
False
True
False
False
False
True


NUMPY COMPLETED