In [ ]:
#numpy practice

In [ ]:
import numpy as np #1.element wise addition
a=np.array([2,4,5,6,7,8])
b=np.array([1,3,6,8,9,6])
print(np.add(a,b))

[ 3  7 11 14 16 14]


In [ ]:
a=np.array(5) # multiply scalar with matrix
c=np.array([[1,2],[3,4]])
print(np.multiply(a,c))

[[ 5 10]
 [15 20]]


In [ ]:
#identity matrix of 4 by 4
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.array([1,2,3,4,5],ndmin=3))


[[[1 2 3 4 5]]]


In [ ]:
a=np.array([1.2,4.5,6.7,8.9],dtype=int)
print(a)

[1 4 6 8]


In [ ]:
print(np.array([1,0,0,1,1],dtype=bool))

[ True False False  True  True]


In [ ]:
a=np.arange(4,8)
a1=a.reshape(2,2)
aa=np.arange(14,18)
a11=a.reshape(2,2)
print(np.hstack((a1,a11)))


[[4 5 4 5]
 [6 7 6 7]]


In [ ]:
print(np.vstack((a1,a11)))

[[4 5]
 [6 7]
 [4 5]
 [6 7]]


In [ ]:
print(np.arange(0,101,2))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
a=np.array([1,2,3,5,6])
b=np.array([9,7,6,5,4])
print(np.where(a==b))

(array([3]),)


In [ ]:
print(np.linspace(0,100,5))

[  0.  25.  50.  75. 100.]


In [ ]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [ ]:
a=np.array([[1,2],[2,3]])
print(np.full((10,2,2),a))

[[[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]

 [[1 2]
  [2 3]]]


In [ ]:
a=np.random.randint(0,11,25)
print(a.reshape(5,5))

[[ 3  9  9  1  3]
 [10  0  1  0  9]
 [ 3  4  3  1  1]
 [ 6  8  6  3  3]
 [ 5  1  6  6 10]]


In [ ]:
a=np.random.normal(0,10,(3,3))
print(a)

[[ 3.18091939  1.92091312 -4.50726078]
 [25.85062278  7.76557513 -5.47952312]
 [-8.16907701  5.25673916  1.29983497]]


In [ ]:
a=np.array([[1,2],[2,3]])
b=np.array([[5,6],[6,8]])
print(np.dot(a,b))

[[17 22]
 [28 36]]


In [ ]:
a=np.array([[1,2],[9,4]])
print(a.transpose())

[[1 9]
 [2 4]]


In [ ]:
print(a)
print(np.sin(a*np.pi/180))

[[1 2]
 [9 4]]
[[0.01745241 0.0348995 ]
 [0.15643447 0.06975647]]


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(a,b))

[[0.97341717 0.98386991]
 [0.89701211 0.8731977 ]]


In [ ]:
a=np.array([2,3,4,5,6,67,2,3,90])
print(np.argsort(a))  #argsort() returns 

[0 6 1 7 2 3 4 5 8]
